spring.main.banner-mode=off
spring.main.web-application-type=none

app.api.generate-webhook-url=https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA
app.api.test-webhook-url=https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA
app.question.one.url=https://drive.google.com/file/d/1IeSI6l6KoSQAFfRihIT9tEDICtoz-G/view
app.question.two.url=https://drive.google.com/file/d/143MR5cLFrlNEuHzzWJ5RHnEWuijuM9X/view
app.credentials.name=Ayaan Khan
app.credentials.reg-no=ADT23SOCB0272
app.credentials.email=k.ayaan1244@gmail.com
app.http.timeout.seconds=30
